apiVersion: nais.io/v1
kind: Alert
metadata:
  name: samhandling-alerts
  namespace: default
  labels:
    team: pensjonsamhandling
spec:
  receivers:
    slack:
      channel: '#samhandling-alerts'
  alerts:
    - alert: App nede
      expr: up{app=~"peproxy|pip-tpforhold|tpregisteret|tjenestepensjon-simulering|tpconfig|samordning-ereg|samordning-inn|samordning-ut|dsop-ufo|pensr|pen-kafka-integration|samordning-hendelse-api|samordning-hendelse-innlasting",job="black box scraping of ingresses"} == 0
      for: 5m
      description: "{{ $labels.app }} er nede i {{ $labels.kubernetes_namespace }}"
      action: Feilsøk årsaken
      severity: danger
    - alert: Database feil
      expr: increase(tpforhold_db_error_counter_total{app=~"pip-tpforhold",job="kubernetes-pods"}[5m]) > 0
      for: 5m
      description: "{{ $labels.app }} i {{ $labels.kubernetes_namespace }} får feil mot databasen"
      action: Feilsøk årsaken og sjekk credentials
      severity: warning
