apiVersion: nais.io/v1
kind: Alert
metadata:
  name: q1-alerts-for-tpordninger
  namespace: default
  labels:
    team: pensjonsamhandling
spec:
  receivers:
    slack:
      channel: '#testmiljø-tjenestepensjon'
  alerts:
    - alert: App nede
      expr: up{app=~"samordning-inn|tpregisteret",job="black box scraping of ingresses"} == 0
      for: 5m
      description: "{{ $labels.app }} er nede i {{ $labels.kubernetes_namespace }}"
      action: Sjekk logger i Q1 her - https://logs.adeo.no/goto/df6e36529831a8f79533b296c2741efc
      severity: danger



    - alert: Samordningsdata
      expr: increase(counter_soap_fault_samordningsdata_sikkerhet{app=~"samordning-inn",job="kubernetes-pods"}[5m]) > 0
      for: 2m
      description: "{{ $labels.app }}({{ $labels.kubernetes_namespace }}): Sikkerhetsfeil mot Samordningsdata"
      action: Undersøk om det er feiler på vår side - https://logs.adeo.no/goto/df6e36529831a8f79533b296c2741efc
      severity: danger

    - alert: Samordningsdata
      expr: increase(counter_soap_fault_samordningsdata_generisk{app=~"samordning-inn",job="kubernetes-pods"}[5m]) > 0
      for: 2m
      description: "{{ $labels.app }}({{ $labels.kubernetes_namespace }}): Generisk SOAP fault mot Samordningsdata"
      action: Undersøk feilen i loggene - https://logs.adeo.no/goto/df6e36529831a8f79533b296c2741efc
      severity: danger



    - alert: LagreTPYtelse
      expr: increase(counter_soap_fault_lagretpforhold_sikkerhet{app=~"samordning-inn",job="kubernetes-pods"}[5m]) > 0
      for: 2m
      description: "{{ $labels.app }}({{ $labels.kubernetes_namespace }}): Sikkerhetsfeil mot LagreTPYtelse"
      action: Undersøk om det er feiler på vår side - https://logs.adeo.no/goto/df6e36529831a8f79533b296c2741efc
      severity: danger

    - alert: LagreTPYtelse
      expr: increase(counter_soap_fault_lagretpforhold_generisk{app=~"samordning-inn",job="kubernetes-pods"}[5m]) > 0
      for: 2m
      description: "{{ $labels.app }}({{ $labels.kubernetes_namespace }}): Generisk SOAP fault mot LagreTPYtelse"
      action: Undersøk feilen i loggene - https://logs.adeo.no/goto/df6e36529831a8f79533b296c2741efc
      severity: danger

